from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
from rdkit import Chem

from openmm import unit

if TYPE_CHECKING:
    from poly_csp.forcefield.export_bundle import ExportBundle


def _is_donor_heavy(atom: Chem.Atom) -> bool:
    if atom.GetAtomicNum() not in {7, 8, 16}:
        return False
    return any(neighbor.GetAtomicNum() == 1 for neighbor in atom.GetNeighbors())


def _is_amide_nitrogen(atom: Chem.Atom) -> bool:
    if atom.GetAtomicNum() != 7:
        return False
    for neighbor in atom.GetNeighbors():
        if neighbor.GetAtomicNum() != 6:
            continue
        bond = atom.GetOwningMol().GetBondBetweenAtoms(atom.GetIdx(), neighbor.GetIdx())
        if bond is None or bond.GetBondType() != Chem.BondType.SINGLE:
            continue
        for other in neighbor.GetNeighbors():
            if other.GetIdx() == atom.GetIdx() or other.GetAtomicNum() != 8:
                continue
            carbonyl_bond = atom.GetOwningMol().GetBondBetweenAtoms(
                neighbor.GetIdx(),
                other.GetIdx(),
            )
            if carbonyl_bond is not None and carbonyl_bond.GetBondType() == Chem.BondType.DOUBLE:
                return True
    return False


def _is_acceptor(atom: Chem.Atom) -> bool:
    atomic_num = atom.GetAtomicNum()
    if atom.GetFormalCharge() > 0:
        return False
    if atomic_num == 8:
        return True
    if atomic_num == 7:
        if _is_amide_nitrogen(atom):
            return False
        if atom.GetTotalValence() >= 4:
            return False
        return True
    if atomic_num == 16:
        return atom.GetTotalValence() <= 6
    return False


def autodock_atom_type(atom: Chem.Atom) -> str:
    atomic_num = atom.GetAtomicNum()
    if atomic_num == 1:
        if atom.GetDegree() == 1 and _is_donor_heavy(atom.GetNeighbors()[0]):
            return "HD"
        return "H"
    if atomic_num == 6:
        return "A" if atom.GetIsAromatic() else "C"
    if atomic_num == 7:
        return "NA" if _is_acceptor(atom) else "N"
    if atomic_num == 8:
        return "OA" if _is_acceptor(atom) else "O"
    if atomic_num == 16:
        return "SA" if _is_acceptor(atom) else "S"
    if atomic_num == 15:
        return "P"
    if atomic_num == 9:
        return "F"
    if atomic_num == 17:
        return "Cl"
    if atomic_num == 35:
        return "Br"
    if atomic_num == 53:
        return "I"
    raise ValueError(
        f"Unsupported AutoDock atom typing for atom {atom.GetIdx()} ({atom.GetSymbol()})."
    )


def _pdbqt_record_name(atom: Chem.Atom) -> str:
    info = atom.GetPDBResidueInfo()
    if info is not None and info.GetIsHeteroAtom():
        return "HETATM"
    return "ATOM"


def _pdbqt_atom_name(atom: Chem.Atom) -> str:
    if atom.HasProp("_poly_csp_atom_name"):
        return atom.GetProp("_poly_csp_atom_name")[:4]
    info = atom.GetPDBResidueInfo()
    if info is not None and info.GetName().strip():
        return info.GetName().strip()[:4]
    return f"{atom.GetSymbol()}{atom.GetIdx() + 1}"[:4]


def _pdbqt_residue(atom: Chem.Atom) -> tuple[str, str, int]:
    info = atom.GetPDBResidueInfo()
    if info is not None:
        return (
            (info.GetResidueName().strip() or "MOL")[:3],
            (info.GetChainId().strip() or "A")[:1],
            int(info.GetResidueNumber()) if info.GetResidueNumber() else 1,
        )
    if atom.HasProp("_poly_csp_selector_instance"):
        return "SEL", "B", int(atom.GetIntProp("_poly_csp_selector_instance"))
    if atom.HasProp("_poly_csp_residue_index"):
        return "GLC", "A", int(atom.GetIntProp("_poly_csp_residue_index")) + 1
    return "MOL", "A", 1


def write_receptor_pdbqt(bundle: ExportBundle, path: str | Path) -> dict[str, object]:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)

    coords_nm = np.asarray(
        bundle.positions_nm.value_in_unit(unit.nanometer),
        dtype=float,
    ).reshape((-1, 3))
    coords_A = coords_nm * 10.0

    lines = [
        "REMARK  Generated by poly_csp from the canonical full runtime system",
        "REMARK  Charges come directly from the OpenMM NonbondedForce",
    ]
    for atom_idx, atom in enumerate(bundle.mol.GetAtoms()):
        atom_type = autodock_atom_type(atom)
        residue_name, chain_id, residue_number = _pdbqt_residue(atom)
        x, y, z = coords_A[atom_idx]
        charge_e = bundle.nonbonded_particles[atom_idx].charge_e
        record_name = _pdbqt_record_name(atom)
        atom_name = _pdbqt_atom_name(atom)
        lines.append(
            f"{record_name:<6}{atom_idx + 1:>5d} {atom_name:<4s} {residue_name:>3s} "
            f"{chain_id:1s}{residue_number:>4d}    "
            f"{x:>8.3f}{y:>8.3f}{z:>8.3f}"
            f"{0.00:>6.2f}{0.00:>6.2f}{charge_e:>8.3f} {atom_type:<2s}"
        )
    lines.extend(["TER", "END"])

    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total_charge_e = sum(p.charge_e for p in bundle.nonbonded_particles)
    return {
        "enabled": True,
        "backend": "native_openmm_charge_export",
        "file": str(target),
        "atom_count": int(bundle.mol.GetNumAtoms()),
        "total_charge_e": float(total_charge_e),
    }
