from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from rdkit import Chem

from poly_csp.config.schema import HelixSpec


@dataclass(frozen=True)
class VinaBoxSpec:
    buffer_A: float = 6.0
    window_residues: int | None = None


@dataclass(frozen=True)
class VinaBox:
    center_x: float
    center_y: float
    center_z: float
    size_x: float
    size_y: float
    size_z: float
    residue_indices: tuple[int, ...]
    heavy_atom_count: int


def _dp_from_mol(mol: Chem.Mol) -> int:
    if mol.HasProp("_poly_csp_dp"):
        return int(mol.GetIntProp("_poly_csp_dp"))
    residue_indices = [
        int(atom.GetIntProp("_poly_csp_residue_index"))
        for atom in mol.GetAtoms()
        if atom.HasProp("_poly_csp_residue_index")
    ]
    if not residue_indices:
        raise ValueError("Cannot derive docking residue window because residue indices are absent.")
    return max(residue_indices) + 1


def _window_residue_indices(
    dp: int,
    helix: HelixSpec,
    spec: VinaBoxSpec,
) -> tuple[int, ...]:
    window = (
        int(spec.window_residues)
        if spec.window_residues is not None
        else int(helix.repeat_residues or 1)
    )
    window = max(1, min(window, dp))
    start = max(0, (dp - window) // 2)
    return tuple(range(start, start + window))


def _heavy_atom_indices_for_window(
    mol: Chem.Mol,
    residue_indices: tuple[int, ...],
) -> list[int]:
    residue_set = set(int(item) for item in residue_indices)
    atom_indices: list[int] = []
    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() == 1:
            continue
        if not atom.HasProp("_poly_csp_residue_index"):
            continue
        if int(atom.GetIntProp("_poly_csp_residue_index")) in residue_set:
            atom_indices.append(int(atom.GetIdx()))
    return atom_indices


def build_vina_box(
    mol: Chem.Mol,
    *,
    helix: HelixSpec,
    spec: VinaBoxSpec,
) -> VinaBox:
    if mol.GetNumConformers() == 0:
        raise ValueError("Vina box generation requires a conformer on the final receptor.")

    residue_indices = _window_residue_indices(_dp_from_mol(mol), helix, spec)
    atom_indices = _heavy_atom_indices_for_window(mol, residue_indices)
    if not atom_indices:
        raise ValueError(
            f"No heavy atoms were found for Vina docking window residues {residue_indices!r}."
        )

    coords = np.asarray(mol.GetConformer(0).GetPositions(), dtype=float).reshape((-1, 3))
    selected = coords[np.asarray(atom_indices, dtype=int)]
    mins = selected.min(axis=0)
    maxs = selected.max(axis=0)
    center = 0.5 * (mins + maxs)
    size = (maxs - mins) + 2.0 * float(spec.buffer_A)

    return VinaBox(
        center_x=float(center[0]),
        center_y=float(center[1]),
        center_z=float(center[2]),
        size_x=float(size[0]),
        size_y=float(size[1]),
        size_z=float(size[2]),
        residue_indices=residue_indices,
        heavy_atom_count=len(atom_indices),
    )


def write_vina_box(box: VinaBox, path: str | Path) -> dict[str, object]:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AutoDock Vina search box arguments generated by poly_csp",
        f"--center_x {box.center_x:.3f}",
        f"--center_y {box.center_y:.3f}",
        f"--center_z {box.center_z:.3f}",
        f"--size_x {box.size_x:.3f}",
        f"--size_y {box.size_y:.3f}",
        f"--size_z {box.size_z:.3f}",
    ]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "file": str(target),
        "center": [box.center_x, box.center_y, box.center_z],
        "size": [box.size_x, box.size_y, box.size_z],
        "residue_indices": list(box.residue_indices),
        "heavy_atom_count": int(box.heavy_atom_count),
    }
